// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXE9awiryh1kMHWPw6jk_2_9hmommcN9k',
    appId: '1:654487520700:web:e006b9ba31d7e0b55697b9',
    messagingSenderId: '654487520700',
    projectId: 'ai-eru-tawasol',
    authDomain: 'ai-eru-tawasol.firebaseapp.com',
    storageBucket: 'ai-eru-tawasol.firebasestorage.app',
    measurementId: 'G-KZFTD3D120',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4wPQ4OLhvsrTAROAAgVLYMkWq4uTHWi4',
    appId: '1:654487520700:android:e4609fcbade386745697b9',
    messagingSenderId: '654487520700',
    projectId: 'ai-eru-tawasol',
    storageBucket: 'ai-eru-tawasol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfwIyqG2LZRXsMLXLBDUd4IkHTFS0Os68',
    appId: '1:654487520700:ios:fc3806414c0841735697b9',
    messagingSenderId: '654487520700',
    projectId: 'ai-eru-tawasol',
    storageBucket: 'ai-eru-tawasol.firebasestorage.app',
    iosBundleId: 'com.example.aiEruTawasol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfwIyqG2LZRXsMLXLBDUd4IkHTFS0Os68',
    appId: '1:654487520700:ios:fc3806414c0841735697b9',
    messagingSenderId: '654487520700',
    projectId: 'ai-eru-tawasol',
    storageBucket: 'ai-eru-tawasol.firebasestorage.app',
    iosBundleId: 'com.example.aiEruTawasol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXE9awiryh1kMHWPw6jk_2_9hmommcN9k',
    appId: '1:654487520700:web:24c4c996725620125697b9',
    messagingSenderId: '654487520700',
    projectId: 'ai-eru-tawasol',
    authDomain: 'ai-eru-tawasol.firebaseapp.com',
    storageBucket: 'ai-eru-tawasol.firebasestorage.app',
    measurementId: 'G-MZRG81C3QX',
  );
}
